-- Haberler data/haberler.json'dan "Article" tablosuna taşınıyor. Şema panelin
-- ihtiyaç duyduğu birkaç alanı taşımıyordu; temalarda olduğu gibi JSONB'ye
-- gömmek yerine sütun açıldı ki veri sorgulanabilir ve tipli kalsın.

-- Kapak görseli dosyada düz bir yol ("/temalar/x.jpg"); şemadaki coverMediaId
-- bir "Media" satırı bekliyor, taşınan haberlerin öyle bir kaydı yok.
ALTER TABLE "Article" ADD COLUMN "coverImage" TEXT NOT NULL DEFAULT '';

-- Editör gövdeyi html ya da düz metin olarak alıyor; düz metin girildiyse
-- kaynak metin de saklanıyor, düzenlemeye geri yüklenebilsin diye.
ALTER TABLE "Article" ADD COLUMN "format" TEXT NOT NULL DEFAULT 'html';
ALTER TABLE "Article" ADD COLUMN "source" TEXT NOT NULL DEFAULT '';

-- WordPress kategori kimlikleri; karttaki etiket bunlardan çözülüyor.
ALTER TABLE "Article" ADD COLUMN "categories" INTEGER[] NOT NULL DEFAULT '{}';

/* Sayısal kimlik. Tablonun birincil anahtarı cuid ve öyle kalıyor (revizyonlar
   ona bağlı), ama uygulamanın haber kimliği WordPress'ten devraldığı sayı:
   /yonetim/icerik/[id] adresleri ve [...slug] rotasında haberlerin statik
   WordPress sayfalarıyla aynı tipte birleşmesi buna dayanıyor. IDENTITY "BY
   DEFAULT" seçildi ki göç betiği dosyadaki kimlikleri olduğu gibi yazabilsin. */
ALTER TABLE "Article" ADD COLUMN "refNo" INTEGER GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX "Article_refNo_key" ON "Article" ("refNo");

/* Taşınan haberlerin yazarı yok: dosyada böyle bir alan hiç olmadı ve panel
   düzenlerken de yazar sormuyor. Zorunlu bırakmak, olmayan bir veriyi uydurup
   hepsini rastgele bir kullanıcıya yazmak demekti. */
ALTER TABLE "Article" ALTER COLUMN "authorId" DROP NOT NULL;

-- Haberlerde tekil kategori alanı kullanılmıyor; kategoriler dizide.
ALTER TABLE "Article" ALTER COLUMN "category" SET DEFAULT '';
