import type { ResourceRow } from "@/components/resource-table";
export const eventRows:ResourceRow[]=[{id:"e1",title:"GençTek Zirvesi 2026",subtitle:"Zirve · Ankara",status:"Yayında",meta:"13–14 Nisan 2026"},{id:"e2",title:"Oyunun e Hâli",subtitle:"Atölye · Ankara",status:"Zamanlanmış",meta:"19 Aralık 2026"},{id:"e3",title:"Siber Güvenlik Yarışması",subtitle:"Yarışma · Çevrimiçi",status:"Taslak",meta:"Tarih bekleniyor"}];
export const themeRows:ResourceRow[]=[{id:"t1",title:"Oyun Tasarımı – EğitiJAM",subtitle:"2025–2026 eğitim yılı",status:"Aktif",meta:"12 içerik"},{id:"t2",title:"Yapay Zekâ",subtitle:"2025–2026 eğitim yılı",status:"Aktif",meta:"18 içerik"},{id:"t3",title:"Açık Kaynak",subtitle:"2025–2026 eğitim yılı",status:"Aktif",meta:"7 içerik"}];
export const coordinatorRows:ResourceRow[]=[{id:"c1",title:"Ayşe Yılmaz",subtitle:"İl Koordinatörü",status:"Aktif",meta:"Ankara"},{id:"c2",title:"Mehmet Kaya",subtitle:"Komisyon Üyesi",status:"Aktif",meta:"Eskişehir"},{id:"c3",title:"Hakkâri",subtitle:"Koordinatör atanmamış",status:"Atama bekliyor",meta:"—"}];
export const mediaRows:ResourceRow[]=[{id:"m1",title:"zirve-2026-kapak.webp",subtitle:"1600 × 900 · WebP",status:"Hazır",meta:"284 KB · 3 kullanım"},{id:"m2",title:"genctek-logo.svg",subtitle:"SVG · Kurumsal varlık",status:"Hazır",meta:"18 KB · 9 kullanım"},{id:"m3",title:"etkinlik-fotograf-01.jpg",subtitle:"2400 × 1600 · JPG",status:"İşleniyor",meta:"3,2 MB"}];
export const documentRows:ResourceRow[]=[{id:"d1",title:"EğitiJAM Bilgi Notu",subtitle:"PDF · v2.1",status:"Yayında",meta:"1,4 MB · 12 Haz 2026"},{id:"d2",title:"Sahne Senin Bilgi Notu",subtitle:"PDF · v1.3",status:"Yayında",meta:"860 KB · 02 May 2026"},{id:"d3",title:"Kurumsal Logo Paketi",subtitle:"ZIP · v1",status:"Taslak",meta:"8,2 MB"}];
export const formRows:ResourceRow[]=[{id:"f1",title:"GençTek Katılım Formu",subtitle:"Sürüm 3 · 13 alan",status:"Yayında",meta:"46 yeni başvuru"},{id:"f2",title:"Paydaş Başvuru Formu",subtitle:"Sürüm 1 · 11 alan",status:"İncelemede",meta:"8 yeni başvuru"}];
export const userRows:ResourceRow[]=[{id:"u1",title:"Selin Yılmaz",subtitle:"selin.yilmaz@meb.gov.tr · Sistem Yöneticisi",status:"Aktif",meta:"MFA açık · bugün"},{id:"u2",title:"Can Demir",subtitle:"can.demir@meb.gov.tr · Editör",status:"Aktif",meta:"MFA açık · 2 gün önce"},{id:"u3",title:"Ece Kaya",subtitle:"ece.kaya@meb.gov.tr · Yayıncı",status:"Davet gönderildi",meta:"3 gün kaldı"}];
export const auditRows:ResourceRow[]=[{id:"a1",title:"article.publish",subtitle:"Selin Yılmaz · GençTek Ankara–Düzce G2S",status:"Başarılı",meta:"Bugün 11.42"},{id:"a2",title:"submission.reveal",subtitle:"Form İnceleyici · GT-20260801-AF31",status:"Başarılı",meta:"Bugün 10.18"},{id:"a3",title:"auth.login_failure",subtitle:"can.demir@meb.gov.tr · IP maskelendi",status:"Reddedildi",meta:"Dün 21.04"}];
