export type ThemeProgram = {
  eyebrow: string;
  title: string;
  summary: string;
  sourceUrl: string;
  sourceLabel: string;
  facts: { value: string; label: string }[];
  highlights: string[];
};

export const themePrograms: Record<string, ThemeProgram> = {
  "g2s-genc-sektor-bulusmalari": { eyebrow:"Resmî program modeli", title:"Gençlerle sektör arasında doğrudan köprü", summary:"G2S; bilişim sektöründeki uzmanları geleceğin sektör liderleri olacak öğrencilerle yüz yüze veya çevrim içi buluşturan GençTek formatıdır. Yazılım geliştirme, oyun tasarımı ve espor gibi alanlarda seri buluşmalar düzenlenmiştir.", sourceUrl:"https://genctek.eba.gov.tr/g2s-genc-sektor-bulusmalari-26-agustos-yazilim-gelistirme/", sourceLabel:"G2S Yazılım Geliştirme buluşması", facts:[{value:"G2S",label:"Genç Sektör Buluşmaları"},{value:"3+",label:"çevrim içi sektör serisi"},{value:"K12",label:"öğrenci ve danışmanlar"}], highlights:["Uzmanlarla doğrudan soru-cevap ve meslek tanıma","Sektördeki gerçek roller ve çalışma süreçleri","Kariyer farkındalığı, rol model ve mentör bağlantısı"] },
  "ritim-ai-yapay-zeka-araclari": { eyebrow:"Uşak tema uygulaması", title:"Yapay zekâ araçlarıyla bir şarkının tüm dünyasını üret", summary:"Ritim a.i. çalışmasında söz, müzik, şarkının hikâyesi ve kapak görseli dahil eser bileşenleri yapay zekâ araçlarıyla geliştirildi. Çevrim içi seminer öğrencileri üretim araçlarıyla tanıştırırken Uşak toplantısı yarışma hazırlıklarını ele aldı.", sourceUrl:"https://genctek.eba.gov.tr/genctek-usak-yapay-zeka-araclari-ve-ritim-a-i/", sourceLabel:"GençTek Uşak Ritim a.i. toplantısı", facts:[{value:"18.02",label:"2025 Uşak buluşması"},{value:"10",label:"katılımcı okul"},{value:"4",label:"eser bileşeni"}], highlights:["Yapay zekâ ile söz, müzik, hikâye ve kapak üretimi","Araç tanıtımları ve yaratıcı üretim semineri","Sahne Senin paylaşımları ve yarışma planlaması"] },
  "dijital-sanatlar": { eyebrow:"Zonguldak tema uygulaması", title:"Grafikten 3B modele, görselden videoya dijital üretim", summary:"GençTek Dijital Sanatlar çalışma grubu; grafik tasarım, 3B tasarım, video ve animasyon alanlarında çalışan öğrencileri buluşturdu. Zonguldak toplantısında yapay zekâ istemleri, metinden görsel ve görselden video üretimi uygulamalı işlendi.", sourceUrl:"https://genctek.eba.gov.tr/genctek-zonguldak-dijital-sanatlar-temali-tanisma-toplantisi/", sourceLabel:"Zonguldak Dijital Sanatlar toplantısı", facts:[{value:"30.04",label:"2025 buluşması"},{value:"3B",label:"modelleme atölyesi"},{value:"AI",label:"yaratıcı üretim araçları"}], highlights:["Grafik tasarım, animasyon, video ve 3B modelleme","Yaratıcı istem yazma ve metinden görsel üretme","Üniversite, teknopark ve kültür paydaşlarıyla buluşma"] },
  "bilisim-hukuku-guvenli-internet": { eyebrow:"Balıkesir tema uygulaması", title:"Dijital haklar, etik ve güvenli internet", summary:"Balıkesir’de öğrenciler; bilişim hukuku uzmanları, akademisyenler, Siberay ekibi ve genç girişimcilerle yapay zekâ etiği, bilişim hukuku ve güvenli internet kullanımı üzerine çalıştı.", sourceUrl:"https://genctek.eba.gov.tr/genctek-balikesir-bilisim-hukuku-ve-guvenli-internet-temali-tanisma-toplantisi-tamamlandi/", sourceLabel:"Balıkesir Bilişim Hukuku toplantısı", facts:[{value:"81",label:"öğrenci"},{value:"21",label:"öğretmen"},{value:"18.04",label:"2025 buluşması"}], highlights:["Yapay zekâ ve etik üzerine öğrenci görüşleri","Bilişim hukuku ve güvenli internet oturumları","Uzmanlara doğrudan soru sorma ve iş fikri paylaşımı"] },
  "tek-maraton": { eyebrow:"Bursa tema uygulaması", title:"Eğitim teknolojileri için fikir maratonu", summary:"Tek Maraton, öğrencilerin eğitim teknolojileri sektörüne yönelik çözüm ve fikir geliştirdiği bir ideathon modelidir. Bursa uygulamasında ekipler yapay zekâ, artırılmış gerçeklik, oyunlaştırma ve dijital içerik alanlarında sürdürülebilir çözümler geliştirdi.", sourceUrl:"https://genctek.eba.gov.tr/genctek-bursa-tek-maraton-egitim-teknolojileri-fikir-maratonu-tamamlandi/", sourceLabel:"Bursa Tek Maraton sonuçları", facts:[{value:"22.04",label:"2025 maratonu"},{value:"4",label:"teknoloji odağı"},{value:"7",label:"ana ve tematik ödül"}], highlights:["Takım çalışmasıyla yenilikçi ve uygulanabilir fikir geliştirme","Akademisyen, girişimci ve sektör temsilcilerinden geri bildirim","Fikirleri jüriye sunma ve prototip yaklaşımı"] },
  "robot-isletim-sistemi": { eyebrow:"Robotik çalışma alanı", title:"Robot yazılımını takım çalışmasıyla bütünleştir", summary:"GençTek’in robotik temalı il buluşmaları öğrencilerin projelerini sergilemesini, akran ekipleri kurmasını ve robot yazılımı üzerine ortak planlama yapmasını destekler. ROS teması bu üretimi sensör, kontrol ve görev düğümleri etrafında derinleştirir.", sourceUrl:"https://genctek.eba.gov.tr/genctek-kahramanmaras-robotik-temali-tanisma-toplantisi/", sourceLabel:"Kahramanmaraş Robotik toplantısı", facts:[{value:"ROS",label:"ortak robot yazılım çatısı"},{value:"3",label:"algı-karar-hareket katmanı"},{value:"Takım",label:"disiplinler arası üretim"}], highlights:["Robotik projeleri sergileme ve akran paylaşımı","Sensör, kontrol ve otonom görev mimarisi","Simülasyondan fiziksel robota uzanan geliştirme"] },
  "espor": { eyebrow:"G2S çevrim içi seri", title:"Espor sektörünün temsilcileri gençlerle buluşuyor", summary:"G2S Espor Sektörü buluşması, espor hakkında fikir edinmek isteyen öğrenci ve danışman öğretmenleri sektör temsilcileriyle çevrim içi ortamda bir araya getirdi.", sourceUrl:"https://genctek.eba.gov.tr/g2s-genc-sektor-bulusmalari-4-ekim-espor-sektoru/", sourceLabel:"G2S Espor Sektörü buluşması", facts:[{value:"04.10",label:"2025 buluşması"},{value:"20.00",label:"çevrim içi oturum"},{value:"G2S",label:"sektör eşleşmesi"}], highlights:["Espor meslekleri ve sektör deneyimleri","Oyunculuk dışındaki yayın, yönetim ve organizasyon rolleri","Öğrenci ve danışman öğretmenlere açık çevrim içi buluşma"] },
  "robot-futbol-ligi": { eyebrow:"Kayseri tema uygulaması", title:"41 takım robot futbol sahasında", summary:"Kayseri’de Robot Futbol Ligi için 18 okuldan öğrenciler bir araya geldi; devamındaki fikstürde 41 takım ve 205 öğrenci dokuz müsabaka gününde yarışma heyecanını paylaştı.", sourceUrl:"https://genctek.eba.gov.tr/genctek-kayseri-robot-futbol-ligi-musabakalar-basladi/", sourceLabel:"Kayseri Robot Futbol Ligi", facts:[{value:"41",label:"takım"},{value:"205",label:"öğrenci"},{value:"9",label:"müsabaka günü"}], highlights:["Robot tasarımı, kodlama ve maç stratejisi","Kura ve fikstürle ilerleyen lig deneyimi","Takım koordinasyonu, test ve sürekli iyileştirme"] },
  "iha": { eyebrow:"Gaziantep tema uygulaması", title:"Havacılık sistemleri ve İHA odağında buluşma", summary:"Gaziantep İHA temalı toplantısı, GençTek öğrencileri ve danışman öğretmenleri sektör temsilcileriyle Müzeyyen Erkul Bilim Merkezi’nde buluşturdu.", sourceUrl:"https://genctek.eba.gov.tr/?p=27734", sourceLabel:"Gaziantep Havacılık Sistemleri İHA toplantısı", facts:[{value:"29.04",label:"2025 buluşması"},{value:"İHA",label:"havacılık sistemleri"},{value:"G2S",label:"uzman buluşması"}], highlights:["Havacılık sistemlerini uzmanlardan tanıma","İHA proje fikirlerini ve deneyimlerini paylaşma","Güvenli görev planlama ve sektör farkındalığı"] },
  "acik-kaynak": { eyebrow:"TÜBİTAK BİLGEM programı", title:"Açık kaynak, Pardus ve dijital özgürlük", summary:"TÜBİTAK BİLGEM Bilim ve Teknoloji Haftası programında öğrenciler açık kaynak, Pardus ve özgür yazılım odağında uzmanlarla buluştu; açık kaynak ve siber güvenlik çalıştaylarında görüş ve çözüm önerileri geliştirdi.", sourceUrl:"https://genctek.eba.gov.tr/genctek-tubitak-bilgem-bilim-ve-teknoloji-haftasi-programi/", sourceLabel:"TÜBİTAK BİLGEM programı", facts:[{value:"12.03",label:"2026 programı"},{value:"3",label:"çalıştay oturumu"},{value:"Pardus",label:"özgür yazılım odağı"}], highlights:["Açık kaynak ve dijital özgürlük çalıştayı","Pardus ve özgür yazılım ekosistemi","Hack The Idea ile farklı görüşlerden çözüm üretme"] },
  "e-ticaret-e-ihracat": { eyebrow:"İzmir tema uygulaması", title:"Bir iş fikrini markaya ve pazara dönüştür", summary:"İzmir E-Ticaret ve E-İhracat Ideathonu’nda 20 liseden öğrenciler; ürün seçimi, marka konumlandırma, logo, slogan, pazar araştırması, bütçe ve pazarlama stratejileri üzerinden iş fikirleri geliştirdi.", sourceUrl:"https://genctek.eba.gov.tr/genctek-izmir-e-ticaret-ve-e-ihracat-ideathonu-icin-ikinci-kez-bir-araya-geldi/", sourceLabel:"İzmir E-Ticaret ve E-İhracat Ideathonu", facts:[{value:"83",label:"öğrenci"},{value:"20",label:"lise ve öğretmen"},{value:"10",label:"ideathon ekibi"}], highlights:["Ürün seçimi, marka ve pazar araştırması","Bütçe planlama ve pazarlama stratejisi","Sektör mentörleriyle iş fikri geliştirme ve sunma"] },
  "yapay-zeka": { eyebrow:"Konya tema uygulaması", title:"Yapay zekânın üretim ve kariyere etkisini keşfet", summary:"Konya toplantısında öğrenciler yapay zekâ destekli oyunlar geliştirip sundu; yazılımda verimli yapay zekâ kullanımı, üretken yapay zekânın medya ve reklama etkisi ile değişen kariyer yolları ele alındı.", sourceUrl:"https://genctek.eba.gov.tr/genctek-konya-yapay-zeka-temali-tanisma-toplantisi/", sourceLabel:"Konya Yapay Zekâ toplantısı", facts:[{value:"28.04",label:"2025 buluşması"},{value:"4",label:"üniversite desteği"},{value:"AI",label:"oyun prototipleri"}], highlights:["Yapay zekâ destekli oyun geliştirme ve sunum","Yazılım, medya, reklam ve kariyer etkileri","Üniversite ve sektör uzmanlarıyla deneyim paylaşımı"] },
  "master-tek": { eyebrow:"Temel GençTek etkinliği", title:"Uzman öğretmenler yarışırken rol model olur", summary:"Master Tek, alanında uzman öğretmenlerin verilen temalarda yarışırken takım çalışması, iş birliği ve centilmenlik örneği sergileyerek öğrencilere rol model olduğu GençTek etkinliğidir.", sourceUrl:"https://genctek.eba.gov.tr/genctek-komisyonu-hazirlik-toplantisi/", sourceLabel:"GençTek temel etkinlikleri ve planlama", facts:[{value:"Usta",label:"uzmanlık paylaşımı"},{value:"Takım",label:"iş birliği"},{value:"Rol model",label:"öğrenciye rehberlik"}], highlights:["Öğretmen uzmanlığını görünür ve paylaşılır kılma","Takım çalışması ve centilmenlik kültürü","Öğrenciler için uygulamalı rol model oluşturma"] },
  "dijital-yuruyus-stem": { eyebrow:"Resmî GençTek etkinlik modeli", title:"Gerçek dünya problemlerine STEM çözümleri", summary:"Dijital Yürüyüş; öğrencilerin gerçek dünya problemlerine ekip halinde çözüm üretip çalışmalarını jüri ve akranlarıyla paylaştığı STEM etkinliğidir. Amasya ve Karaman uygulamaları tarihî ve kültürel değerleri teknolojiyle buluşturdu.", sourceUrl:"https://genctek.eba.gov.tr/wp-content/uploads/2026/01/Dijital-Yuruyus-STEM-Bilgi-Notu-GencTek.pdf", sourceLabel:"Dijital Yürüyüş STEM bilgi notu", facts:[{value:"STEM",label:"4 disiplin"},{value:"Saha",label:"gerçek dünya problemi"},{value:"Jüri",label:"çözüm sunumu"}], highlights:["Sorgulama, araştırma ve disiplinler arası üretim","Yerel kültür ve çevreden problem keşfi","Ekip çözümünü jüriye ve akranlara sunma"] },
  "dijital-bagimliliklara-sosyal-fiziksel-alternatif": { eyebrow:"Manisa tema uygulaması", title:"Ekran karşısına sosyal ve fiziksel alternatifler", summary:"İlk GençTek Manisa toplantısında dijital bağımlılığın farklı boyutları; dijital detoks, ekransız bir gün, çevrim içinden çevrim dışına geçiş, öz denetim ve sosyal-fizyolojik etkiler üzerinden değerlendirildi.", sourceUrl:"https://genctek.eba.gov.tr/genctek-manisa-tanisma-toplantisi/", sourceLabel:"GençTek Manisa tanışma toplantısı", facts:[{value:"12.12",label:"2024 buluşması"},{value:"O2O",label:"online'dan offline'a"},{value:"Denge",label:"dijital esenlik"}], highlights:["Dijital detoks ve ekransız gün fikirleri","Öz denetim ve dengeli teknoloji kullanımı","Sosyal ve fiziksel etkinlik alternatifleri"] },
};

export function getThemeProgram(slug: string) { return themePrograms[slug]; }
